### PR TITLE
feat: support loading config from JS and JSON files

### PR DESCRIPTION
**Pull request by duro**
This PR builds upon what was started in PR #159 and adds tests

Fixes: #292

### CODE REVIEW

**Comment by duro** [comment]
@horike37 @theburningmonk Could I get a review on this. Seems it is a feature that has been desired since January of last year.

**Comment by theburningmonk** [comment]
@duro thanks for the PR, it looks fine to me at a glance, have you tried it out with an actual serverless.js file to see if it works?

**Comment by duro** [comment]
@theburningmonk, yes, in fact I'm already using my fork in a project

**Pull request merged**
