### PR TITLE
feature: support lambda_proxy req template

### LINKED ISSUE #162: Get path parameters from API Gateway
How can I pass the _**user_id**_ as the initial input to the step function?

```
stepFunctions:
  stateMachines:
    hellostepfunc:
      name: HelloStep
      events:
        - http:
            path: notes/{user_id}
            method: GET
            cors: true
            authorizer: aws_iam
      input: {
        user_id: "$.user_id"
      }
```

### PR DESCRIPTION
**Pull request by theburningmonk**
Closes #162

Example JSON payload:
image

```
{
  "body": {
    "x": 42,
    "y": 20
  },
  "httpMethod": "POST",
  "path": "/dev/yan/ada",
  "resource": "/{userId}/{petId}",
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "cache-control": "no-cache",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "GB",
    "Content-Type": "application/json",
    "Host": "w7kv6bolzh.execute-api.us-east-1.amazonaws.com",
    "Postman-Token": "596fe5f1-c826-4878-87b4-e931a50171ca",
    "User-Agent": "PostmanRuntime/7.1.1",
    "Via": "1.1 8d36edc1ce736c158ddedbd7365e2a8e.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "zO79TaMtZ_SE-FAnPr8LB3AKpFr83CiKtrGN2crfJqEdC0TIl6Dg1A==",
    "x-amz-date": "20190504T014853Z",
    "X-Amzn-Trace-Id": "Root=1-5cccef86-ff71e1460c3170319d54e9f5",
    "X-Forwarded-For": "93.115.192.234, 70.132.15.142",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https"
  },
  "queryStringParameters": {
    "food": "felix"
  },
  "pathParameters": {
    "userId": "yan",
    "petId": "ada"
  },
  "requestContext": {
    "accountId": "374852340823",
    "resourceId": "hryv9h",
    "stage": "dev",
    "requestId": "c5ef6a18-6e0e-11e9-9964-d573456a33b9",
    "requestTime": "04/May/2019:01:48:54 +0000",
    "requestTimeEpoch": "1556934534091",
    "identity": {
      "cognitoIdentityPoolId": "",
      "accountId": "",
      "cognitoIdentityId": "",
      "caller": "",
      "sourceIp": "93.115.192.234",
      "principalOrgId": "",
      "accessKey": "",
      "cognitoAuthenticationType": "",
      "cognitoAuthenticationProvider": "",
      "userArn": "",
      "userAgent": "PostmanRuntime/7.1.1",
      "user": ""
    },
    "path": "/dev/yan/ada",
    "resourcePath": "/{userId}/{petId}",
    "httpMethod": "POST",
    "protocol": "HTTP/1.1",
    "apiId": "w7kv6bolzh"
  },
  "stageVariables": {}
}
```

Example form-urlencoded payload:
image

```
{
  "body": {
    "x": "42",
    "y": "20"
  },
  "httpMethod": "POST",
  "path": "/dev/yan/ada",
  "resource": "/{userId}/{petId}",
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "cache-control": "no-cache",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "GB",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "w7kv6bolzh.execute-api.us-east-1.amazonaws.com",
    "Postman-Token": "bd47fcbd-79d1-4c6a-bba0-4969d024bdf4",
    "User-Agent": "PostmanRuntime/7.1.1",
    "Via": "1.1 c31d49af55fff364fbd11e21a32f7fcb.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "e9dPZoRXXkyXr0F-6RQ5O6r3vfRgdf2aP0ejSBIEvmRgmwOjzHIoIA==",
    "x-amz-date": "20190504T090435Z",
    "X-Amzn-Trace-Id": "Root=1-5ccd55a3-97e75c5904b7a19d6b83be20",
    "X-Forwarded-For": "93.115.192.234, 70.132.15.54",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https"
  },
  "queryStringParameters": {
    "food": "felix"
  },
  "pathParameters": {
    "userId": "yan",
    "petId": "ada"
  },
  "requestContext": {
    "accountId": "374852340823",
    "resourceId": "hryv9h",
    "stage": "dev",
    "requestId": "a37ea84d-6e4b-11e9-b15d-8b1127e053a3",
    "requestTime": "04/May/2019:09:04:35 +0000",
    "requestTimeEpoch": "1556960675610",
    "identity": {
      "cognitoIdentityPoolId": "",
      "accountId": "",
      "cognitoIdentityId": "",
      "caller": "",
      "sourceIp": "93.115.192.234",
      "principalOrgId": "",
      "accessKey": "",
      "cognitoAuthenticationType": "",
      "cognitoAuthenticationProvider": "",
      "userArn": "",
      "userAgent": "PostmanRuntime/7.1.1",
      "user": ""
    },
    "path": "/dev/yan/ada",
    "resourcePath": "/{userId}/{petId}",
    "httpMethod": "POST",
    "protocol": "HTTP/1.1",
    "apiId": "w7kv6bolzh"
  },
  "stageVariables": {}
}
```

### CODE REVIEW

**Comment by horike37** [comment]
Great work! Thanks @theburningmonk 👍 
Could you add the explanation of this new option to README as well?

**Comment by theburningmonk** [comment]
@horike37 done! also fixed most of the linter errors in the README and a mistake (from me) from the previous PR where I should have `Fn::GetAtt` instead of `Ref` for Lambda function ARNs.

**Comment by andrhamm** [comment]
Awesome!

**Comment by andrhamm** [comment]
I just gave this a try and noticed a few subtle differences when compared to the API Gateway -> Lambda proxy template:

1. the value of `body` is an object rather than a JSON encoded string
2. the `requestContext.domainName` is missing
3. data types and default values are inconsistent (numeric vs string valeus, `""` or `{}` instead of `null` in many cases)
4. `multiValueQueryStringParameters` and `multiValueHeaders` are not present

This is a great start and most of these are easily handled, it just makes dual-purpose functions a bit more work.

**Comment by theburningmonk** [comment]
@andrhamm do you have an example I can use to root out these differences? Some of them are pretty straight forward, like turning `body` into a string and adding `requestContext.domainName`, but it'll be good to get an example for like-for-like comparison

**Comment by andrhamm** [comment]
@theburningmonk i created a mock serverless app here to demonstrate the differences in the event payloads: https://github.com/andrhamm/mock-dual-purpose-lambda

**Comment by theburningmonk** [comment]
Thank you @andrhamm that's very useful!

**Pull request merged**
