### PR TITLE
Fix VTL simple quote escaping

### LINKED ISSUE #140: Bug in ApiGateway Template: apostrophe results in parsing error
# This is a Bug Report

It looks like in the stepfunctions api gateway template is the same error as here:  https://github.com/serverless/serverless/pull/2993/files

## Description
If an ' (apostrophe) inside the request, it will always fail. 

For bug reports:
* What went wrong?
JSON parsing wrong.
* What did you expect should have happened?
A valid JSON must be accepted and redirected to the StepFunction
* What was the config you used?
```
    ApiGatewayCall:
      name: ${self:service}-${opt:stage, self:provider.stage}-ApiGatewayCall
      timeout: 100 # optional, in seconds, default is 6

      events:
        - http:
            path: import
            method: POST
```
* What stacktrace or error message from your provider did you see?
`{"__type":"com.amazon.coral.service#SerializationException"}`

* ***Provider Error messages***:
```
curl -D - -XPOST -H "Content-Type: application/json; charset=utf-8" https://<endpoint>/dev/import -d "{\"name\":\"Palatto d'Inv\"}"
HTTP/2 400
content-type: application/json
content-length: 60
date: Sun, 05 Aug 2018 19:59:20 GMT
x-amzn-requestid: 0afcd14b-98ea-11e8-ad05-8f443798b4c1
x-amz-apigw-id: LKqL4HhyliAFoYQ=
x-amzn-trace-id: Root=1-5b675718-08e0041dcc5f96d971896ced
x-cache: Error from cloudfront
via: 1.1 affe26bf02a36a4a45ea1eb3ce2b4a62.cloudfront.net (CloudFront)
x-amz-cf-id: 7wbWVgMmsFwHFIFXhJ8S204WSsP2VGDUaRMZngL1nylrr50TqXZP7Q==

{"__type":"com.amazon.coral.service#SerializationException"}
```

### PR DESCRIPTION
**Pull request by thibaultdalban**
Follow up PR of #141 Closes #140

Thanks to @marcelalburg for the initial work done and to @lendesk-pawel-cisek for his advise on how to test it.

### CODE REVIEW

**Comment by tigrish** [comment]
👍

**Comment by theburningmonk** [comment]
@thibaultdalban this looks good to me, although the test doesn't really tell me that it'll work (which is fine, I don't see a way to unit test the correctness of the change). Can you test this out in a real project and print the outline in here to show that it works?

**Comment by thibaultdalban** [comment]
@theburningmonk yes unfortunately it's not easy to unit test the change.
Find below the output of the API Gateway test method for the following input payload:
```json
{ "foobar": "I'm going to make him an offer he can't refuse."}
```
- Before the fix:
```
Method request body before transformations: { "foobar": "I'm going to make him an offer he can't refuse."}
...
Endpoint request body after transformations: {"input": "{\"foobar\":\"I\'m going to make him an offer he can\'t refuse.\"}", ...}
```
- After the fix:
```
Method request body before transformations: { "foobar": "I'm going to make him an offer he can't refuse."}
...
Endpoint request body after transformations: {"input": "{\"foobar\":\"I'm going to make him an offer he can't refuse.\"}", ...}
```

**Comment by theburningmonk** [comment]
Excellent. Just tested this myself, whereas a payload like this `{ "messageId": "ab", "message": "Palatto d'Inv" }` would have thrown a serialization error before, now it works as expected.

Good work!

**Pull request merged**
