### PR TITLE
feat: add support for AuthorizationScopes

### LINKED ISSUE #200: Setting Oauth scope in Api Gateway does not work for step functions
have a step function with http event configured. I am using Cognito authorizer and using oauth scopes. Syntax is the same as with Lambda and API Gateway configuration (which works correctly).

Example of cfg:

```yaml
stepFunctions:
  stateMachines:
    calculate:
            events:
            - http:
                path: v1/calculate
                method: POST
                cors: true
                authorizer:
                  name: authorizer
                  arn: 'arn'
                  identitySouce: method.request.header.Authorization
                  scopes: 
                    - 'scope1'
```

## Additional Data

* ***Serverless Framework Version you're using***:   1.42.3
* ***Provider Error messages***:  deployment works well, authorizer is set but scope is not set
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by theburningmonk**
Closes #200

### CODE REVIEW

**Comment by theburningmonk** [comment]
@gregadunbit mind taking a peep at this? especially the test cases

**Comment by gregadunbit** [comment]
@theburningmonk will look into it first thing tomorrow morning.

**Comment by gregadunbit** [comment]
@horike37 can you trigger release for a version with this feature so that I can test it?

**Comment by theburningmonk** [comment]
@gregadunbit done!

**Comment by gregadunbit** [comment]
It doesn't work for me:



@theburningmonk 

This is the syntax which I use for apigw and lambdas:

```yml
events:
        - http:
            path: v1/calculate
            method: POST
            cors: true
            authorizer:
              name: authorizer
              arn: arn:aws:cognito-idp:eu-west-1:xxxxxxxxxx
              identitySouce: method.request.header.Authorization
              scopes: 
                - scope1
```

I tried to add also

```yml
events:
        - http:
            path: v1/calculate
            method: POST
            cors: true
            authorizer:
              name: authorizer
              type: COGNITO_USER_POOLS
              arn: arn:aws:cognito-idp:eu-west-1:732945622201:userpool/eu-west-1_XvVw9TFBh
              identitySouce: method.request.header.Authorization
              scopes: 
                - scope 1
```

Does not work for an existing stack and also for new.

**Comment by gregadunbit** [comment]
I think the problem is in this line:

https://github.com/horike37/serverless-step-functions/blob/07a62777970e95299506f8ad0a3453a677a63736/lib/deploy/events/apiGateway/methods.js#L326

Probably it should be:

if (http.authorizer.type && (http.authorizer.authorizerId || http.authorizer.name) ) {

**Comment by theburningmonk** [comment]
I think that case is for when you use "Custom", but your case should be handled by this line: https://github.com/horike37/serverless-step-functions/blob/07a62777970e95299506f8ad0a3453a677a63736/lib/deploy/events/apiGateway/methods.js#L342-L345

**Comment by theburningmonk** [comment]
but I also don't see what we do with the `identitySouce` field, don't think that's supported either!

**Comment by theburningmonk** [comment]
Also, what's the `name` property supposed to signify?

**Comment by gregadunbit** [comment]
name is set in Authorization field in Method Request in APIGW.

You are right about the code. Is it somehow possible that  awsArnRegExs.
cognitoIdpArnExpr.test(authorizerArn)) does not work well?

**Comment by gregadunbit** [comment]
https://github.com/horike37/serverless-step-functions/blob/07a62777970e95299506f8ad0a3453a677a63736/lib/utils/arnRegularExpressions.js#L4

Should be

cognitoIdpArnExpr: /arn:[a-zA-Z-]*:cognito-idp/,

without ^ ?

**Comment by theburningmonk** [comment]
@gregadunbit no that wouldn't be it, since `^` just asserts the start, although I'm curious why the `lambdaArnExpr` doesn't have it?

just tested it quickly and it should still match
image

**Comment by theburningmonk** [comment]
ok, I think I found the problem, scopes is stripped out before it even reached the `getMethodAuthorization` method!

**Pull request merged**
