### PR TITLE
Feature/support tagging

### PR DESCRIPTION
**Pull request by theburningmonk**
PR for #166 now that CloudFormation supports tagging for Step Functions

### CODE REVIEW

**Comment by noahw3** [comment]
Looks like this matches the cloudformation template exactly, but it might be nicer syntactically to define the tags as a dictionary (like how lambdas work) and then internally convert it to the array of key/value pairs?

**Comment by theburningmonk** [comment]
@noahw3 I thought about that too, but I have actually seen teams use `:` as delimiter in the key. There's nothing stopping us from still using `:` as delimiter though, e.g. `my:namespace:for:tags:value` => `{ Key: "my:namespace:for:tags", Value: "value" }` but it might look a bit old.

But what if `Value` is an ARN which is also delimited by `:`? It would break our parsing. Open to suggestions as to how we might address that.

**Comment by noahw3** [comment]
If a special character is needed in the actual value, quoting it should be sufficient?

**Comment by noahw3** [comment]
Base serverless project implementation: https://github.com/serverless/serverless/blob/00d129ca86febcd960b17b19818ac413f7bee4d9/lib/plugins/aws/package/compile/functions/index.js#L135-L145

**Comment by theburningmonk** [comment]
@noahw3 ahh, I completely misunderstood you! You meant treat it as an object instead of array, of course, that makes sense :-D

**Pull request merged**
