### PR TITLE
Feature/cw events notifications

### LINKED ISSUE #197: Feature: support Status Change notification
# This is a Feature Proposal

## Description

You can monitor the execution of your state machines [via CloudWatch Events](https://aws.amazon.com/about-aws/whats-new/2019/05/aws-step-functions-adds-support-for-workflow-execution-events/) now.

It will be great to add support for it in the plugin so you can configure them alongside your state machine definition, e.g.

```
stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: test
      definition:
        ...
      notifications:
        ABORTED:
          - sns: SNS_TOPIC_ARN
          - sqs: SQS_TOPIC_ARN
          - sqs: # more config options
              arn: SQS_TOPIC_ARN
              messageGroupId: 12345
          - lambda: LAMBDA_FUNCTION_ARN
          - kinesis: KINESIS_STREAM_ARN
          - kinesis:  # more config options
               arn: KINESIS_STREAM_ARN
               partitionKeyPath: $.user_id
          - firehose: FIREHOSE_STREAM_ARN
          - stepFunctions: STATE_MACHINE_ARN
        FAILED:
          ... # same as above
        RUNNING:
          ... # same as above
        SUCCEEDED:
          ... # same as above
        TIMED_OUT:
          ... # same as above
```

### PR DESCRIPTION
**Pull request by theburningmonk**
Closes #197

### CODE REVIEW

**Comment by theburningmonk** [comment]
@horike37 looks like the build is failing due to node 6.2 tests, can we remove that now that node 6 has been deprecated by lambda?

**Comment by horike37** [comment]
@theburningmonk 
Yup, edit .travis.yml so that the tests can be passed 👍

**Comment by theburningmonk** [comment]
@horike37 thanks, that's updated now

**Pull request merged**
