### PR TITLE
add support for new update state machine feature

### PR DESCRIPTION
**Pull request by rplute**
This PR updates functionality for the [new update feature](https://aws.amazon.com/about-aws/whats-new/2017/11/aws-step-functions-adds-support-for-updating-state-machines/) in CloudFormation for Step Function's state machines. It resolves [Issue #87](https://github.com/horike37/serverless-step-functions/issues/87).

You can pass in an optional name and the CloudFormation stack will pass that name to the new `StateMachineName` field on the `AWS::StepFunctions::StateMachine` type. More info [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html). If no optional name is passed, it defaults to the same conventions as before.

I tweaked the unit tests a little to make it all work. I then tested deployments with a name passed and no name passed.

Please feel free to provide feedback or make any modifications as you see fit.

### CODE REVIEW

**Comment by horike37** [comment]
Great! thanks @rplute :+1: That's a long-awaited functionality :100: 
We will take a look into that.

**Comment by syedautherabbas** [comment]
@horike37 , can you please pull this feature add , its much needed.

**Comment by syedautherabbas** [comment]
@rplute thanks for this 👍

**Comment by horike37** [comment]
Thanks @syedautherabbas for pinging me!

I tested locally and great to see working fine!
Awesome work @rplute :+1: 
Additionally, I noticed the bug which invoking functionality was broken when I was not aware that,  and then fixed it.

merging and will release a new version :tada:

**Comment by rplute** [comment]
@horike37 , thanks for testing it out! I assumed I had missed something, somewhere. On a side note, the test coverage on this library is amazing. Great work!

**Pull request merged**
