### PR TITLE
fix: scopes is now passed through validation

### LINKED ISSUE #200: Setting Oauth scope in Api Gateway does not work for step functions
have a step function with http event configured. I am using Cognito authorizer and using oauth scopes. Syntax is the same as with Lambda and API Gateway configuration (which works correctly).

Example of cfg:

```yaml
stepFunctions:
  stateMachines:
    calculate:
            events:
            - http:
                path: v1/calculate
                method: POST
                cors: true
                authorizer:
                  name: authorizer
                  arn: 'arn'
                  identitySouce: method.request.header.Authorization
                  scopes: 
                    - 'scope1'
```

## Additional Data

* ***Serverless Framework Version you're using***:   1.42.3
* ***Provider Error messages***:  deployment works well, authorizer is set but scope is not set
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by theburningmonk**
Closes #200

### CODE REVIEW

**Comment by theburningmonk** [comment]
@gregadunbit this should fix it

**Comment by theburningmonk** [comment]
@gregadunbit this has been deployed in `1.23.1`, care to try again to see if it's working now?

**Comment by gregadunbit** [comment]
@theburningmonk works. Tnx.

**Pull request merged**
