### PR TITLE
feat: support the new Map state

### LINKED ISSUE #257: Support Map State
# This is a Bug Report

## Description

When using this plugin with the new Map state, the state machine IAM role does not include the functions listed under `Iterator:`

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.52.1
* ***The Plugin Version you're using***: 2.7.0

### PR DESCRIPTION
**Pull request by theburningmonk**
Closes #257

### CODE REVIEW

**Comment by jamaica474** [comment]
Map state still doesn't work. As far as I can see it ignores content of "Iterator" key.

Relevant part of config:
deliverBatch: name: deliverBatchPipeline-${opt:stage} definition: Comment: "Delivers batch of postings" StartAt: LOCK_POSTINGS States: LOCK_POSTINGS: Type: Map Iterator: StartAt: MARK_POSTING_AS_PROCESSED States: MARK_POSTING_AS_PROCESSED: Type: Task Resource: Fn::GetAtt: [markProcessed, Arn] End: true End: true

Error: ✕ State machine "deliverBatch" definition is invalid: [{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/fail#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/pass#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/succeed#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/task#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['LOCK_POSTINGS']","schemaPath":"http://asl-validator.cloud/wait#/additionalProperties","params":{"additionalProperty":"Iterator"},"message":"should NOT have additional properties"},{"keyword":"oneOf","dataPath":".States['LOCK_POSTINGS']","schemaPath":"#/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"}]

**Comment by theburningmonk** [comment]
@jamaica474 looks like the latest version of asl-validator hasn't added support for the Map type yet, so for now please disable `validate` until it's added

**Comment by theburningmonk** [comment]
@jamaica474 I opened a PR against asl-validator to add support for Map state type, once it's published I'll update this plugin as well

**Comment by theburningmonk** [comment]
@jamaica474 all the PRs are merged and released, try v2.8.1

**Comment by jamaica474** [comment]
looks great. Thanks a lot, 've been waiting forever for Map state

**Pull request merged**
